// <auto-generated />
using System;
using InventariumAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventariumAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251007141954_brokenobjects_and_constraints")]
    partial class brokenobjects_and_constraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventariumAPI.Models.BrokenObject", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjectId");

                    b.ToTable("BrokenObjects");
                });

            modelBuilder.Entity("InventariumAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InventariumAPI.Models.Lendout", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ObjectId", "UserId");

                    b.HasIndex("ObjectId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Lendouts");
                });

            modelBuilder.Entity("InventariumAPI.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("InventariumAPI.Models.ObjectEntry", b =>
                {
                    b.Property<int>("ObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ObjectId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("InventariumAPI.Models.ObjectManager", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ObjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ObjectManagers");
                });

            modelBuilder.Entity("InventariumAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InventariumAPI.Models.BrokenObject", b =>
                {
                    b.HasOne("InventariumAPI.Models.ObjectEntry", "Object")
                        .WithOne()
                        .HasForeignKey("InventariumAPI.Models.BrokenObject", "ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");
                });

            modelBuilder.Entity("InventariumAPI.Models.Lendout", b =>
                {
                    b.HasOne("InventariumAPI.Models.ObjectEntry", "Object")
                        .WithOne("Lendout")
                        .HasForeignKey("InventariumAPI.Models.Lendout", "ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventariumAPI.Models.User", "User")
                        .WithMany("Lendouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventariumAPI.Models.ObjectEntry", b =>
                {
                    b.HasOne("InventariumAPI.Models.Category", "Category")
                        .WithMany("Objects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventariumAPI.Models.Location", "Location")
                        .WithMany("Objects")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("InventariumAPI.Models.ObjectManager", b =>
                {
                    b.HasOne("InventariumAPI.Models.ObjectEntry", "Object")
                        .WithMany("Managers")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventariumAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventariumAPI.Models.Category", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("InventariumAPI.Models.Location", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("InventariumAPI.Models.ObjectEntry", b =>
                {
                    b.Navigation("Lendout");

                    b.Navigation("Managers");
                });

            modelBuilder.Entity("InventariumAPI.Models.User", b =>
                {
                    b.Navigation("Lendouts");
                });
#pragma warning restore 612, 618
        }
    }
}
